language: python
dist: xenial
python:
- "2.7"
- "3.5"
- "3.6"
install: python setup.py install
script: python setup.py sdist bdist_egg bdist_wheel
deploy:
  provider: pypi
  user: ssmirnov
  skip_existing: true
  password:
    secure: JnBTnS4KSy+TkqQAMXXG8StwxCDwiJ6GcAYb7JtZhQ3NNPMCaUjJ3W3jL0VU3Yen3k6hp4js7kyz1mOO/iXCkPl4FNpNFPlP4LufEmlA8kMV4o9OwHsvPEthxnhddS+K77+5bfv+idi0IWq87TN6sCs/A/rv1IUiOagI1bbIcHqJ4RlKP+5LE+XgJlmVfip4W34RZjqB0rVBDouk3YBOnxuCHKLyo0h/7PUF6/QdMv8aGdUJeuRajzoymJi8ny1cqXd5j0J/XcIBho5AGSDegM7NhHnAlj+QVSWWadi1Gi3piwAfD2nKMx+QjRpdJnm3xjTiGGMbO0yqV/czrRU9RyI10zQZGfl0ALrIQcK+YVIjIdA+pj+BWuVdYN/EwE5vM19Yyx6b0B6yH/Gu/WYIE+nWmNOYGuMCLzybNTDw8BOLEyW7CKyguWMSk+u0bipMZupoVnYFrj1m0FnDbHeqpvKGi066sGnNY9E2Q8o50FRxh1QY1EXkYpE2cFsOMElUhSVIQc6Zlgv3GAWjW8c2fOsI1gKIpp6QavA2cKDCVqg6EuqrFmhTNflHlMbAcmMDICMbZjiFxaBSu0+sQxATEWCpxWF+J5K2Z7I+c6gaRbXe2UO49/UIj4lmv3aGH5v+zlJtwBumPMZj97WnbUMKBdArR8KPtCtThLzx+JRw6gc=
  on:
    tags: true
    distributions: sdist bdist_egg bdist_wheel
    repo: plesk/360agent
