language: python
dist: xenial
python:
- "3.6"
install: python setup.py install
script: python setup.py sdist bdist_egg bdist_wheel
deploy:
  provider: pypi
  username: __token__
  skip_existing: true
  password:
    secure: YoMCo2nBcfS87WjQ0fEgUT1oztPIfkI2JZn6B2z3ne0NyzNVzghoxP2JBtWHMg2rSJJnuh7tC4J83Kelna7RmLbfoA3Luyy4FLV0uVGFszf950rN1It/CK0V0P8eOF2fWaVJOsYqhft9U9qxgSBCy/cKl/oKNwsrim9DdhpUn12FtYACpAOSt2n3P02IUHtYl1c5YObuDQQ++cY5PeoXXVqgMP3PZqUAs9GMUaU3pxyk+IzRynx4iqkpUjwg6PmG0Fd3rCErnF5wH19p2A/qvPRfZLJoCeBjUWQV8MsVI9xwiaP5geYBw6q4aeh826fHc6S0yMQbFpO7oU0dmHDRayAIr6orGLZp/7iKo0G2xgM+eCimamtwA1MUQNpIudl1aGL6fgYEUF7FVYjBI83DHmpuny6UUW2lmmGROsnu35hAZr+uchR9pdHpmaL5gzUTSzV8mFvFWlmYVewka+aicELqdUJO0aVxXKwekRSJmAwE6Oq1KlW7QMvqVN2nsTqM8VBRfKMiMWP3Qfiym7XS8V0HxGh2AlT9AJzFHtg9KqoObeCBH+8K03zKMcvtfs/1Q38XpdbiH+ZN3+fMH0Tvrmfh782wP6MuqYz2uVa6Lxx0uueUpzz8Bd/+oSOd2hBR7DDB3Vt1+oaraq+7wY1gn9wrPsu5uO2cMaF7vF5+2J8=
  on:
    tags: true
    distributions: sdist bdist_egg bdist_wheel
    repo: plesk/360agent
