language: python
dist: focal
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install .
script: python setup.py sdist bdist_egg bdist_wheel
deploy:
  provider: pypi
  username: __token__
  skip_existing: true
  password:
    secure: iwoVAeRiRg5uPQjMbMVUzow7YqQ7W7vnK7ZKKnjmR/0UCf1t7DofLSHZ8xuzmK1lvRD+EpyWZkOkPbU4r4MspAtqEBpdF9C3Oi80SYiEqoj6nmx8x4nlehR1NJjCjxDkiNnYeDefWQHlefIgHH7eHCusxZLz2XrMp4GkKtM367A31LWs0zROHBOoEKSmfqSQKPsjC/kDiAk9impFY8tAZ8fPOZQTIjtmmHKK/lIkfaf+2aTCJrzFO9268R+G4x1bTst8q42g7pefwICFIkrzHigQLytdFovBYo4NUVfYXB6BR6DIEQUelYu2A15JS07/lqHkDjoSm/vzpkoPhGFl1iCzgl2kwFJTcUxUs8qwY9XJ4U8RbxgLQ8ST7vWjNK/SDSRlt1en0idnD7hCSQ/UUEMPKmfmAzzEi1mLxPP2BdZGEFDGnCrLkA476YjgCUewNapdUnk8ir9Tg6muvokdLeJXeCMwbdX678qG9+UVCDAJGZjgvaOP0FzdjM2ZBsj8074SwJjfyozrsKva1ztLoysy5pMKg2SHV0iIDv8cZ1ww+qhkH1G8gNWTlKxeMlpz3h1sQjVWIm9CpBmFXn2VdrQIi9XKy/ypHRmb9G0eTh7LL2qFIFdyuWnOjdMovx1F0hGc9lQ/GBJNPpivI++ekU/3ah8KZSCCRqsZ6PAdTfc=
  on:
    tags: true
    distributions: sdist bdist_egg bdist_wheel
    repo: plesk/agent360
    python: 3.6
